### ISSUE TITLE
Make some good readme for the project

### ISSUE THREAD

**Issue by Aniruddha-Shriwant** [OmkarPh/LiteRecorder#1]

**Comment by OmkarPh** [comment]
I'm not good with READMEs
Can you help me with it?

**Comment by Aniruddha-Shriwant** [comment]
Okay, will make a PR on this soon :)

**Comment by OmkarPh** [comment]
^^

**Comment by Aniruddha-Shriwant** [comment]
I'm bored 😂

**Comment by OmkarPh** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqOvPGRfivzPA5a8qpNoYJe05DXjrnqBIpaw&usqp=CAU
